# Generated by Django 2.2.4 on 2020-11-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(related_name='recents', to='login_reg.User'),
        ),
        migrations.DeleteModel(
            name='Recent',
        ),
    ]
