# Generated by Django 2.2 on 2020-11-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('main', '0004_auto_20201117_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='users',
            new_name='user_recents',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_favs',
            field=models.ManyToManyField(related_name='favorites', to='login_reg.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
